export const techSection = [
  { name: "React", img: "/icons/reactIcon.svg", color: "#61DAFB" },
  { name: "TypeScript", img: "/icons/typeScriptIcon.svg", color: "#3178C6" },
  { name: "NodeJS", img: "/icons/nodeJSIcon.svg", color: "#339933" },
  { name: "Express", img: "/icons/expressIcon.svg", color: "#ffffff" },
  { name: "MongoDB", img: "/icons/mongoDBIcon.svg", color: "#47A248" },
  { name: "React Router", img: "/icons/reactRouterIcon.svg", color: "#CA4245" },
  { name: "Spring Boot", img: "/icons/springBootIcon.svg", color: "#6DB33F" },
  { name: "PostgreSQL", img: "/icons/postgreSQLIcon.svg", color: "#4169E1" },
  { name: "Zustand", img: "/icons/zustandIcon.svg", color: "#433929" },
  { name: "GSAP", img: "/icons/gsapIcon.svg", color: "#88CE02" },
  { name: "Vercel", img: "/icons/vercelIcon.svg", color: "#ffffff" },
  { name: "Render", img: "/icons/renderIcon.svg", color: "#46E3B7" },
  { name: "Neon", img: "/icons/neonIcon.svg", color: "#00E599" },
  { name: "GitHub", img: "/icons/githubIcon.svg", color: "#ffffff" },
  { name: "Vite", img: "/icons/viteIcon.svg", color: "#646CFF" },
];